# Generated by Django 4.2.1 on 2023-05-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updatedBy', models.CharField(max_length=200)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
