# Generated by Django 4.2.1 on 2023-05-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updatedBy',
        ),
    ]
